#!/bin/bash

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  Created by xXxuserxXx on xXxdatexXx.
#  All code (c) xXxyearxXx - present day, xXxownerxXx.
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

source Dependencies/ReleaseTools/Scripts/make-tools

echo "***************"
echo "Releasing macOS"
echo "***************"

set -o pipefail

rt set scheme ActionStatus-Sparkle --platform macOS
rt archive --xcconfig Sources/ActionStatus/Resources/IncludeSparkle.xcconfig 2>/dev/null | xcpretty
rt export --distribution true
rt notarize
rt wait
rt compress
rt publish
