#!/bin/bash

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  Created by xXxuserxXx on xXxdatexXx.
#  All code (c) xXxyearxXx - present day, xXxownerxXx.
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

if [[ ("$ACTION" == "install") && ("$RT_BUILD" == "100") ]]
then
    echo "error: trying to archive with Sparkle testing turned on."
    exit 1
fi
