#!/bin/bash

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  Created by xXxuserxXx on xXxdatexXx.
#  All code (c) xXxyearxXx - present day, xXxownerxXx.
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

#export RT_REBUILD=true
source Dependencies/ReleaseTools/Scripts/make-tools

echo "***************"
echo "Preparing macOS"
echo "***************"

rt set scheme ActionStatus-macOS --platform macOS
rt archive --xcconfig Sources/ActionStatus/Resources/SkipSparkle.xcconfig  | xcpretty
rm -rf ~/Desktop/ActionStatusNoSparkle.app
ditto ".build/macOS/archive.xcarchive/Products/Applications/Action Status.app" ~/Desktop/ActionStatusNoSparkle.app
open ~/Desktop/ActionStatusNoSparkle.app
