#!/bin/bash

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  Created by xXxuserxXx on xXxdatexXx.
#  All code (c) xXxyearxXx - present day, xXxownerxXx.
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

xcodebuild -workspace xXxprojectCamelxXx.xcworkspace/ -scheme Tools | xcpretty

echo " "
echo "*************"
echo "Uploading iOS  "
echo "*************"

set -euox pipefail  # (add an x to flags to enable debugging)

echo "Using release tools $(rt --version)."
rt set scheme xXxprojectCamelxXx --platform=iOS
rt archive --platform=iOS --show-output 2> /dev/null | xcpretty
rt export --platform=iOS
rt upload --platform=iOS
